import type { Metadata } from "next";
import { PageMotion } from "@/components/PageMotion";
import { SiteFooter, SiteNav } from "@/components/SiteChrome";

export const metadata: Metadata = { title: "About — Chulda", description: "SaaS, AI, and digital product motion designer." };
const capabilities = ["Creative direction", "Product storytelling", "Motion systems", "UI animation", "Storyboarding", "Styleframes", "3D direction", "Sound direction"];
const tools = ["After Effects", "Cinema 4D", "Figma", "Illustrator", "Photoshop", "Premiere Pro", "Rive", "GSAP"];

export default function AboutPage() { return <PageMotion className="about-page"><div className="route-nav-reveal"><SiteNav /></div><section className="route-hero about-hero"><div className="about-portrait route-hero-art scale-reveal"><div className="portrait-field"><i /><i /><i /><span>C</span></div></div><div><div className="route-line-clip"><h1 className="route-hero-line">I understand</h1></div><div className="route-line-clip"><h1 className="route-hero-line"><em>before I animate.</em></h1></div><p className="route-hero-copy">I’m Chulda, a motion designer focused on making SaaS, AI, and digital products clearer, more engaging, and more memorable.</p></div></section><section className="about-belief"><p>My philosophy</p><h2>Motion is not the finish applied after product thinking. It is part of how the product explains itself.</h2></section><section className="about-columns"><article className="stack-card"><span>Experience</span><h2>From product logic to launch story.</h2><p>I work across strategy, visual development, animation, and sound—connecting the decisions that make product communication feel coherent.</p></article><article className="stack-card"><span>Creative values</span><h2>Clear. Intentional. Useful.</h2><p>Restraint creates confidence. Curiosity creates attention. Detail creates trust. The work should quietly demonstrate all three.</p></article></section><section className="capability-grid"><div><p>Capabilities</p>{capabilities.map(item=><span key={item}>{item}</span>)}</div><div><p>Software</p>{tools.map(item=><span key={item}>{item}</span>)}</div></section><section className="resume-strip"><p>Selected experience and credentials</p><a href="mailto:hello@chulda.graphics?subject=Resume%20request">Request résumé <span>↗</span></a></section><SiteFooter nextLabel="Let’s work together." nextHref="/contact" /></PageMotion>; }
